run:
  # timeout for analysis, e.g. 30s, 5m, default is 1m
  timeout: 5m

linters:
  # please, do not use `enable-all`: it's slow and may report obscure issues
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - goimports
    - revive

issues:
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
